import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Degen Marketing",
    description: "Generated by Locofy Lightning",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
        <script src="https://tally.so/widgets/embed.js" async></script>
    </head>
    <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
